#floriantschopp/schneith, 07/2019
#!/bin/bash

# Check for arguments
if [ -z "$1" ]; then
  echo "Disable the warnings generated by the eigen core headers by adding pragma's to all header files.";
  echo -e "Usage: disable_warnings.sh CATKIN_DEVEL_SPACE/EIGEN_SYSTEM_INCLUDE"
  exit -1
fi

DEVEL_SPACE=$1
EIGEN_INCLUDES_DIR=$1/include/eigen3
CURR_DIR=$(pwd -P)
TEMPLATE_DIR=$(pwd -P)/template
cd $EIGEN_INCLUDES_DIR
CORE_DIR=$(pwd -P)/Eigen/src/Core
cd $CURR_DIR

echo "Attempt to change headers in $CORE_DIR"

# Now check if gtsam headers are installed and the path is correct
if [ ! -d "$EIGEN_INCLUDES_DIR" ] || [ ! -f "$CORE_DIR/ArrayBase.h" ]; then
  echo "Could not find eigen headers in the specified devel space!";
  exit -1
fi

# Check wheter the warnings are already disabled
ALREADY_IGNORED=$(cat $CORE_DIR/ArrayBase.h | grep "pragma GCC diagnostic ignored \"-Wint-in-bool-context\"" | wc -l)
if [ "$ALREADY_IGNORED" -eq "1" ]; then
  echo "Warnings are already disabled, you only need to run this script once!";
  echo "To revert to the original state you can clean and rebuild the eigen_catkin package or reinstall system eigen.";
  exit -1
fi

# Now recursivly add the header and footer to the headers
find $CORE_DIR -name "*.h" -print0 | xargs -0 -I file sh -c "cat $TEMPLATE_DIR/header file $TEMPLATE_DIR/footer > file.new; mv file.new file"
echo "Successfully modified headers to disable the warnings."
echo "To revert to the original state you can clean and rebuild the eigen_catkin package.";
